# Generated by Django 4.1.5 on 2023-01-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='topic')),
                ('description', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Topic Section',
                'verbose_name_plural': 'Topic Sections',
                'db_table': 'topic_section',
            },
        ),
    ]
